// Code generated by "stringer -type=Scope"; DO NOT EDIT.

package techniques

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Row-0]
	_ = x[Column-1]
	_ = x[Box-2]
}

const _Scope_name = "RowColumnBox"

var _Scope_index = [...]uint8{0, 3, 9, 12}

func (i Scope) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Scope_index)-1 {
		return "Scope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scope_name[_Scope_index[idx]:_Scope_index[idx+1]]
}
